# Generated by Django 2.0 on 2021-05-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20210528_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.SlugField(),
        ),
    ]
