# Generated by Django 2.0 on 2021-05-29 13:35

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20210529_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=1200)),
        ),
    ]
